version: '3.4'
services:
  react-nginx-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8081:80
    environment:
      - CHOKIDAR_USEPOLLING=true